baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "zafta"
#hasCJKLanguage = true
defaultContentLanguage = "en"
author = "ee"
# Define the number of posts per page
paginate = 4

[params.company]
name = "Monifa"


[permalinks]
	page = "/:title/"
	about = "/:filename/"
    post = "/blog/:slug"

	
[Languages]
[Languages.en]
title = "Multilingual Hugo Example"
weight = 0
languagename = "English"

[[Languages.en.menu.main]]
#url = "/"
#name = "Home"
#weight = 1

[[Languages.en.menu.main]]
url = "/about/"
name = "About us"
weight = 2

[[Languages.en.menu.main]]
url = "/writing/"
name = "Writing"
weight = 3

[[Languages.en.menu.main]]
url = "/contact/"
name = "Contact"
weight = 4


[[Languages.en.menu.main]]
url = "/blog/"
name = "Blog"
weight = 5

[Languages.nl]
title = "Multilingual Hugo Example"
weight = 1
languagename = "Dutch"

[[Languages.nl.menu.main]]
#url = "/"
#name = "Huis"
#weight = 1

[[Languages.nl.menu.main]]
url = "/nl/over/"
name = "Over ons"
weight = 2

[[Languages.nl.menu.main]]
url = "/nl/artikelen/"
name = "Artikelen"
weight = 3

[[Languages.nl.menu.main]]
url = "/nl/contact/"
name = "Contact"
weight = 4

[[Languages.nl.menu.main]]
url = "/nl/blog/"
name = "Blog"
weight = 5


[[Languages.en.menu.footer]]
url = "/colophon/"
name = "Colophon"
weight = 1

[[Languages.en.menu.footer]]
url = "/terms-of-use"
name = "Terms of Use"
weight = 2

[[Languages.en.menu.footer]]
url = "/privacy-policy"
name = "Privacy Policy"
weight = 3

[[Languages.nl.menu.footer]]
url = "/colofon/"
name = "Colofon"
weight = 1

[[Languages.nl.menu.footer]]
url = "/gebruiksvoorwaarden"
name = "Gebruiksvoorwaarden"
weight = 2

[[Languages.nl.menu.footer]]
url = "/privacybeleid"
name = "Privacybeleid"
weight = 3