baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "zafta"
#hasCJKLanguage = true
defaultContentLanguage = "en"


[permalinks]
	page = "/:title/"
	about = "/:filename/"

	
[Languages]
[Languages.en]
title = "Multilingual Hugo Example"
weight = 0
languagename = "English"

[[Languages.en.menu.main]]
url = "/"
name = "Home"
weight = 1

[[Languages.en.menu.main]]
url = "/about/"
name = "About"
weight = 2

[[Languages.en.menu.main]]
url = "/journal/"
name = "Journal"
weight = 3

[[Languages.en.menu.main]]
url = "/contact/"
name = "Contact"
weight = 4

[Languages.nl]
title = "Multilingual Hugo Example"
weight = 1
languagename = "Dutch"

[[Languages.nl.menu.main]]
url = "/"
name = "Huis"
weight = 1

[[Languages.nl.menu.main]]
url = "/nl/over/"
name = "Over"
weight = 2

[[Languages.nl.menu.main]]
url = "/nl/dagboek/"
name = "Dagboek"
weight = 3

[[Languages.nl.menu.main]]
url = "/nl/contact/"
name = "Contact"
weight = 4


[[Languages.en.menu.footer]]
url = "/colophon/"
name = "Colophon"
weight = 1

[[Languages.en.menu.footer]]
url = "/terms-of-use"
name = "Terms of Use"
weight = 2

[[Languages.en.menu.footer]]
url = "/privacy-policy"
name = "Privacy Policy"
weight = 3

[[Languages.nl.menu.footer]]
url = "/colofon/"
name = "Colofon"
weight = 1

[[Languages.nl.menu.footer]]
url = "/gebruiksvoorwaarden"
name = "Gebruiksvoorwaarden"
weight = 2

[[Languages.nl.menu.footer]]
url = "/privacybeleid"
name = "Privacybeleid"
weight = 3