backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  
publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "data/settings.json"
        description: "General Site Settings"
        fields:
          - label: "English Page News Subscription"
            name: En_Page_Subscription
            widget: "object"
            fields:
              - {label: "Title", name: "subscription_title", widget: "string"}
              - {label: "Sub Title", name: "sub_title", widget: "string"}
              - {label: "Placeholder Text", name: "placeholder_text", widget: "string"}
              - {label: "Button Text", name: "button_text", widget: "string"}
          - label: "Dutch Page News Subscription"
            name: Nl_Page_Subscription
            widget: "object"
            fields:
              - {label: "Title", name: "subscription_title", widget: "string"}
              - {label: "Sub Title", name: "sub_title", widget: "string"}
              - {label: "Placeholder Text", name: "placeholder_text", widget: "string"}
              - {label: "Button Text", name: "button_text", widget: "string"}
          - label: "English Footer News Subscription"
            name: En_footer_Subscription
            widget: "object"
            fields:
              - {label: "Title Hightlight text", name: "highlight_title", widget: "string"}
              - {label: "Main Title", name: "main_title", widget: "string"}
              - {label: "Sub Title", name: "sub_title", widget: "string"}
              - {label: "Placeholder Text", name: "placeholder_text", widget: "string"}
              - {label: "Button Text", name: "button_text", widget: "string"}
          - label: "Dutch Footer News Subscription"
            name: Nl_footer_Subscription
            widget: "object"
            fields:
              - {label: "Title Hightlight text", name: "highlight_title", widget: "string"}
              - {label: "Main Title", name: "main_title", widget: "string"}
              - {label: "Sub Title", name: "sub_title", widget: "string"}
              - {label: "Placeholder Text", name: "placeholder_text", widget: "string"}
              - {label: "Button Text", name: "button_text", widget: "string"}
  - name: "pages"
    label: "Pages"
    create: true # Allow users to create new documents in this collection
    files:
      - file: "content/_index.en.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/_index.nl.md"
        label: "Home Dutch"
        name: "home_Nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Date, name: date, widget: date}
          - {label: Slug, name: slug, widget: string}
          - {label: Type, name: Type, widget: string}
          - {label: "What we about", name: we_about, widget: object, fields: [
              {label: "Heading Left", name: "heading_left", widget: "string", tagname: "p"},
              {label: "Text", name: "text_right", widget: "markdown"}]}
          - {label: "How We get help", name: get_help, widget: object, fields: [
              {label: "Heading Left", name: "heading_left", widget: "string", tagname: "p"},
              {label: "Text", name: "text_right", widget: "markdown"}]}
          - {label: "Who we are", name: who_are, widget: object, fields: [
              {label: "Heading Left", name: "heading_left", widget: "string", tagname: "p"},
              {label: "Text", name: "text_right", widget: "markdown"}]}
          - {label: "Testimonials", name: testimonials, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: Body, name: body, widget: markdown}
      - file: "content/about.nl.md"
        label: "About NL"
        name: "about_nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Date, name: date, widget: date}
          - {label: Slug, name: slug, widget: string}
          - {label: Type, name: Type, widget: string}
          - {label: "What we about", name: we_about, widget: object, fields: [
              {label: "Heading Left", name: "heading_left", widget: "string", tagname: "p"},
              {label: "Text", name: "text_right", widget: "markdown"}]}
          - {label: "How We get help", name: get_help, widget: object, fields: [
              {label: "Heading Left", name: "heading_left", widget: "string", tagname: "p"},
              {label: "Text", name: "text_right", widget: "markdown"}]}
          - {label: "Who we are", name: who_are, widget: object, fields: [
              {label: "Heading Left", name: "heading_left", widget: "string", tagname: "p"},
              {label: "Text", name: "text_right", widget: "markdown"}]}
          - {label: "Testimonials", name: testimonials, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: Body, name: body, widget: markdown}
      - file: "content/colophon.md"
        label: "Colophon"
        name: "colophon"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/colophon.nl.md"
        label: "Colophon NL"
        name: "colophon_nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/writing.nl.md"
        label: "Writing nl"
        name: "writing_nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Sub Title, name: subTitle, widget: string}
          - {label: description, name: description, required: false,  widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: "Side Bar", name: "sidebar", widget: "boolean", default: false}
          - {label: "Sidebar Date", name: "sidebar_date", widget: "date", default: false}
          - {label: "Sidebar Content", name: sidebar_Content, default: false,  widget: list, fields: [
              {label: "Filled text", name: "filled_text", widget: "string"},
              {label: "Filled Url", name: "filled_url", widget: "string"}]}
          - {label: Body, name: body, widget: markdown}
      - file: "content/writing.md"
        label: "Writing"
        name: "writing_en"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Sub Title, name: subTitle, widget: string}
          - {label: description, name: description, required: false,  widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: "Side Bar", name: "sidebar", widget: "boolean", default: false}
          - {label: "Sidebar Date", name: "sidebar_date", widget: "date", default: false}
          - {label: "Sidebar Content", name: sidebar_Content, default: false,  widget: list, fields: [
              {label: "Filled text", name: "filled_text", widget: "string"},
              {label: "Filled Url", name: "filled_url", widget: "string"}]}
          - {label: Body, name: body, widget: markdown}
      - file: "content/privacy-policy.md"
        label: "privacy policy"
        name: "privacy_policy"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/privacy-policy.nl.md"
        label: "privacy policy nl "
        name: "privacy_policy_nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/terms-of-use.md"
        label: "Terms of Use "
        name: "terms_of_use"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/terms-of-use.nl.md"
        label: "Terms of use Dutch"
        name: "terms_of_use_nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/thank-you.md"
        label: "thank-you"
        name: "thank-you"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: type, name: type, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/thank-you.nl.md"
        label: "thank-you"
        name: "thank-you_nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: type, name: type, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: date, name: date, widget: string}
          - {label: slug, name: slug, widget: string}
          - {label: type, name: type, widget: string}
          - {label: form, name: form, widget: string}
          - {label: "Contact Form", name: contact_form, widget: object, fields: [
              {label: Name, name: name_label, widget: string},
              {label: Email, name: email_label, widget: string},
              {label: Subject, name: subject_label, widget: string},
              {label: Message, name: message_label, widget: string},
              {label: Submit Text, name: submit_text, widget: string},
              {label: Placeholder Name, name: placeholder_name, widget: string},
              {label: Placeholder Email, name: placeholder_email, widget: string},
              {label: Placeholder Subject, name: placeholder_subject, widget: string},
              {label: Placeholder Message, name: placeholder_message, widget: string}]}
      - file: "content/contact.nl.md"
        label: "Contact Page NL"
        name: "contact_nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: date, name: date, widget: string}
          - {label: slug, name: slug, widget: string}
          - {label: type, name: type, widget: string}
          - {label: form, name: form, widget: string}
          - {label: "Contact Form", name: contact_form, widget: object, fields: [
              {label: Name, name: name_label, widget: string},
              {label: Email, name: email_label, widget: string},
              {label: Subject, name: subject_label, widget: string},
              {label: Message, name: message_label, widget: string},
              {label: Submit Text, name: submit_text, widget: string},
              {label: Placeholder Name, name: placeholder_name, widget: string},
              {label: Placeholder Email, name: placeholder_email, widget: string},
              {label: Placeholder Subject, name: placeholder_subject, widget: string},
              {label: Placeholder Message, name: placeholder_message, widget: string}]}
      - file: "content/final-step.md"
        label: "Final Step"
        name: "final_step"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Subtitle Light, name: subtitleLight, widget: string}
          - {label: date, name: date, widget: string}
          - {label: slug, name: slug, widget: string}
          - {label: type, name: type, widget: string}
          - {label: form, name: form, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/final-step.nl.md"
        label: "Final Step Dutch"
        name: "final_step_nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Subtitle Light, name: subtitleLight, widget: string}
          - {label: date, name: date, widget: string}
          - {label: slug, name: slug, widget: string}
          - {label: type, name: type, widget: string}
          - {label: form, name: form, widget: string}
          - {label: Body, name: body, widget: markdown}