backend:
  name: git-gateway
  
publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.en.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/_index.nl.md"
        label: "À propos de moi"
        name: "home Nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Type, name: Type, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/about.nl.md"
        label: "About NL"
        name: "over"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Type, name: Type, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/colophon.md"
        label: "Colophon"
        name: "Colophon"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/colophon.nl.md"
        label: "Colophon NL"
        name: "Colophon NL"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/Journal.nl.md"
        label: "Journal nl"
        name: "Journal Nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/Journal.md"
        label: "Journal"
        name: "Journal"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/privacy-policy.md"
        label: "privacy policy"
        name: "privacy policy"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/privacy-policy.nl.md"
        label: "privacy policy nl "
        name: "privacy policy nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/terms-of-use.md"
        label: "terms-of-use "
        name: "terms-of-use"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/terms-of-use.nl.md"
        label: "terms-of-use nl"
        name: "terms-of-use nl"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: description, name: description, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/thank-you.md"
        label: "thank-you"
        name: "thank-you"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: type, name: type, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/thank-you.nl.md"
        label: "thank-you"
        name: "thank-you"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - {label: Date, name: date, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: type, name: type, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: image}
          - {label: date, name: date, widget: string}
          - {label: slug, name: slug, widget: string}
          - {label: type, name: type, widget: string}
          - {label: form, name: form, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: name, name: name, widget: string}
          - {label: email, name: email, widget: string}
          - {label: subject, name: subject, widget: string}
          - {label: message, name: message, widget: string}
          - {label: submitText, name: submitText, widget: string}
          - {label: placeholderName, name: placeholderName, widget: string}
          - {label: placeholderEmail, name: placeholderEmail, widget: string}
          - {label: placeholderSubject, name: placeholderSubject, widget: string}
          - {label: placeholderMessage, name: placeholderMessage, widget: string}
      - file: "content/contact.nl.md"
        label: "Contact Page NL"
        name: "contact NL"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: image}
          - {label: date, name: date, widget: string}
          - {label: slug, name: slug, widget: string}
          - {label: type, name: type, widget: string}
          - {label: form, name: form, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: name, name: name, widget: string}
          - {label: email, name: email, widget: string}
          - {label: subject, name: subject, widget: string}
          - {label: message, name: message, widget: string}
          - {label: submitText, name: submitText, widget: string}
          - {label: placeholderName, name: placeholderName, widget: string}
          - {label: placeholderEmail, name: placeholderEmail, widget: string}
          - {label: placeholderSubject, name: placeholderSubject, widget: string}
          - {label: placeholderMessage, name: placeholderMessage, widget: string}